[package]
name = "common-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "local-time",
    "chrono",
] }
tracing-appender = "0.2.5"
tracing = "0.1.44"
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
